CentOS 6.5 RDO
==============
yum install http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
yum install http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-3.noarch.rpm

#### Only if using foreman 1.5 ####
yum install centos-release-SCL 
yum install scl-utils
#### Only if using foreman 1.5 ####

RHEL 6.5 OSP 4
==============

# If using Subscription Manager:

subscription-manager register --auto-attach
subscription-manager repos --disable=*
subscription-manager repos --enable=rhel-6-server-rpms --enable=rhel-6-server-rh-common-rpms --enable=rhel-6-server-openstack-4.0-rpms --enable=rhel-lb-for-rhel-6-server-rpms --enable=rhel-6-server-optional-rpms

# If using RHN Classic:

rhn_register
rhn-channel --add --channel=rhel-x86_64-server-6-rhscl-1
rhn-channel --add --channel=rhel-x86_64-server-6-ost-4

yum -y update
yum -y install openstack-foreman-installer dhcp foreman-selinux foreman-sqlite

RHEL 7 OSP 5 (No Foreman, just Packstack)
=========================================

subscription-manager register --auto-attach
subscription-manager repos --disable=*
subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-openstack-5.0-rpms --enable=rhel-7-server-rh-common-rpms
yum -y update
yum -y install openstack-packstack

RHEL 6.5 OSP 5 (Staypuft / Foreman rhel-osp-installer)
======================================================

# Channels needed for the Installer: http://red.ht/1vBReqa
# Channels needed if synching: subscription-manager repos --enable=rhel-6-server-openstack-foreman-rpms --enable=rhel-6-server-rpms --enable=rhel-6-server-rh-common-rpms --enable=rhel-6-server-openstack-5.0-rpms


subscription-manager register --auto-attach
subscription-manager repos --disable=*
subscription-manager repos --enable=rhel-6-server-openstack-foreman-rpms --enable=rhel-6-server-rpms --enable=rhel-server-rhscl-6-rpms
yum -y update
yum -y install rhel-osp-installer
