#!/bin/bash

# This file goes in /usr/lib/systemd/hugetlb-reserve-pages

nodes_path=/sys/devices/system/node/
if [ ! -d $nodes_path ]; then
        echo "ERROR: $nodes_path does not exist"
        exit 1
fi

reserve_pages()
{
        echo $1 > $nodes_path/$2/hugepages/hugepages-1048576kB/nr_hugepages
}

reserve_pages 8 node0
reserve_pages 8 node1
