heat_template_version: 2014-10-16
# This template shows how to use cloud-init via OS::Heat::CloudConfig and how to run scripts via OS::Heat::SoftwareConfig

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.

parameters:
  extra_username:
    type: string
    default: extrauser

description: >
  Sets root password and runs wipe-disk.sh on the ceph nodes

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: user_config}
      #- config: {get_resource: wipe_disk}
      #- config: {get_resource: extra_compute_disk}

  user_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        manage-resolv-conf: true
        resolv_conf:
          domain: osp.rh
        ssh_pwauth: True
        disable_root: false
        chpasswd:
          list: |
            root:changeme
          expire: False
  wipe_disk:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: wipe-disk.sh}
  extra_compute_disk:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: prepare-extra-compute-disk.sh}


outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
